name: PR Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  analyze-version-bump:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release and plugins
        run: |
          npm init -y
          npm install --save-dev \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/git \
            conventional-changelog-conventionalcommits

      - name: Analyze commits for version bump
        id: analyze
        run: |
          RESULT=$(npx semantic-release --dry-run --extends=@semantic-release/commit-analyzer 2>&1)
          echo "$RESULT"

          if echo "$RESULT" | grep -q "The next release version is"; then
            TYPE=$(echo "$RESULT" | grep 'The next release version is' | sed -E 's/.*is a ([a-z]+) release.*/\1/')
            echo "version_bump=$TYPE" >> $GITHUB_OUTPUT
          else
            echo "version_bump=none" >> $GITHUB_OUTPUT
          fi

      - name: Print version bump
        run: |
          echo "version_bump? ${{ steps.analyze.outputs.version_bump }}"

      - name: Comment on PR if there is a version bump
        if: ${{ steps.analyze.outputs.version_bump != 'none' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: version-bump-check
          message: |
            🔍 **Semantic Version Check**

            This PR will trigger a **${{ steps.analyze.outputs.version_bump }}** release.
